# Generated by Django 2.1.5 on 2019-02-09 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptGenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wall_time', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=100)),
                ('script_path', models.CharField(max_length=100)),
                ('nodes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('memory', models.CharField(max_length=100)),
                ('CPUs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('MemoryPerCPU', models.CharField(max_length=100)),
            ],
        ),
    ]
